# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

recor_matrix <- function(x, y = NULL) {
    .Call(`_recor_recor_matrix`, x, y)
}

recor_vector <- function(x, y) {
    .Call(`_recor_recor_vector`, x, y)
}

