#' classical function strings
#'
#' @description
#' to do
#' @usage
#' to do
#' @details
#' funs_simon_Tibshirani(): functions utilized by simon Tibshirani
#' 
#' funs_reshef(): functions utilized by reshef
#' 
#' @return popular function names 
#' @references
#' D. N. Reshef, Y. A. Reshef, P. C. Sabeti, M. Mitzenmacher, 
#' An empirical study of the maximal and total information coefficients 
#' and leading measures of dependence. Ann. Appl. Stat. 12, 123–155 (2018).
#' available at: https://doi.org/10.1214/17-AOAS1093SUPPA
#' 
#' H. Jiang, Q. Wu, Robust dependence measure for detecting associations 
#' in large data set. Acta Mathematica Scientia. 38, 57–72 (2018).
#' 
#' 
#' @export
funs_simon_Tibshirani <- function() {
    simon_Tibshirani_functions <- c(line = "y <- x",
                                    quadratic = "y <- 4*(x-0.5)^2", #+ --> - @20220109
                                    cubic = "y <- 128*(x-1/3)^3 - 48*(x-1/3)^2-12*(x-1/3)",
                                    sinusoid_8periods = "y <- sin(16*pi*x)",
                                    sinusoid_2periods = "y <- sin(4*pi*x)",
                                    fourth_root = "y <- x^0.25",
                                    circle = "y <- sqrt(1-(2*x-1)^2)",
                                    step = "y <- 1*(x>0.5)")
    return(simon_Tibshirani_functions)
}

#' @export
funs_reshef <- function() {
    reshef_functions <- c(cosine_high_freq = "y <- cos(14*pi*x)",
                          cosine_nonfourier_freq = "y <- cos(7*pi*x)", 
                          cosine_varying_freq = "y <- cos(5*pi*x*(1+x))",
                          cubic = "y <- 4*(2.4*x - 1.3)^3+(2.4*x - 1.3)^2-4*(2.4*x - 1.3)", 
                          cubic_Ystreteched = "y <- 41*(4*(2.4*x - 1.3)^3+(2.4*x - 1.3)^2-4*(2.4*x - 1.3))",
                          exponential_base10 = "y <- 10^(10*x)", 
                          exponential_base2 = "y <- 2^(10*x)",
                          L_shaped = "y <- x/99*(x<=0.99) + (x > 0.99)",
                          line = "y <- x",
                          linear_plus_periodic = "y <- 0.1*sin(10.6*(2*x-1)) + 1.1*(2*x-1)",
                          linear_plus_periodic2 = "y <- 0.2*sin(10.6*(2*x-1)) + 1.1*(2*x-1)",
                          linear_plus_periodic_low_freq = "y <- 0.2*sin(4*(2*x-1)) +1.1*(2*x-1)", 
                          linear_plus_periodic_medium_freq = "y <- sin(10*pi*x)+x",
                          lopided_Lshaped = "y <- 200*x*(x < 1/200) + (-198*x+199/100)*(x >= 1/200 & x < 1/100) + (-x/99+1/99) *(x>=1/100)",
                          parabola = "y <- 4*(x-0.5)^2",
                          sigmoid = "y <- 0*(x<49/100) + (50*(x-0.5)+0.5) * (x >= 49/100 & x <=51/100) + (x>51/100)",
                          sine_high_freq = "y <- sin(16*pi*x)", 
                          sine_low_freq = "y <- sin(8*pi*x)",
                          sine_nonfourier_freq = "y <- sin(9*pi*x)",
                          sine_varing_freq = "y <- sin(6*pi*x*(1+x))",
                          spike = "y <- 20*(x<1/20) + (-18*x+19/10) * (x>=1/20 & x < 1/10) + (-x/9+1/9)*(x>=1/10)")
    return(reshef_functions)
}


#' @export
selected_y_funs117_with_expressions <- function() {
    y_funs <- c(
        "y <- x",
        "y <- 2*x+1",
        "y <- x^2",
        "y <- sqrt(x)",
        "y <- x^0.25",
        "y <- 1/x",
        "y <- x^3",
        "y <- exp(x)",
        "y <- exp(3*x)",
        "y <- exp(300*x)",
        "y <- 2^(10*x)",
        "y <- 2^(100*x)",
        "y <- 10^(10*x)",
        "y <- 10^(100*x)",
        "y <- log(x)",
        "y <- sin(2*pi*x)",
        "y <- cos(2*pi*x)",
        "y <- tan(pi*(x-0.5))",
        "y <- cot(pi*x)",
        "y <- asin(x)",
        "y <- acos(x)",
        "y <- atan(x)",
        "y <- acot(x)",
        "y <- 4*(x-0.5)^2",
        "y <- 128*(x-1/3)^3 - 48*(x-1/3)^2-12*(x-1/3)",
        "y <- 4*(2.4*x - 1.3)^3+(2.4*x - 1.3)^2-4*(2.4*x - 1.3)",
        "y <- 41*(4*(2.4*x - 1.3)^3+(2.4*x - 1.3)^2-4*(2.4*x - 1.3))",
        "y <- sqrt(1-(2*x-1)^2)",
        "y <- x^100",
        "y <- x^3000",
        "y <- x^-3",
        "y <- x + 1/x",
        "y <- 1*(x>0.5)",
        "y <- as.numeric(x/99*(x<=0.99) + (x > 0.99))",
        "y <- 0*(x<49/100) + (50*(x-0.5)+0.5) * (x >= 49/100 & x <=51/100) + (x>51/100)",
        "y <- 20*(x<1/20) + (-18*x+19/10) * (x>=1/20 & x < 1/10) + (-x/9+1/9)*(x>=1/10)",
        "y <- 200*x*(x < 1/200) + (-198*x+199/100)*(x >= 1/200 & x < 1/100) + (-x/99+1/99) *(x>=1/100)",
        "y <- sin(pi/2*x)",
        "y <- sin(4*pi*x)",
        "y <- sin(8*pi*x)",
        "y <- sin(9*pi*x)",
        "y <- sin(16*pi*x)",
        "y <- cos(pi/2*x)",
        "y <- cos(7*pi*x)",
        "y <- cos(14*pi*x)",
        "y <- tan(pi/2*x)",
        "y <- cot(pi/2*x)",
        "y <- sin(6*pi*x*(1+x))",
        "y <- cos(5*pi*x*(1+x))",
        "y <- sec(pi/2*x)",
        "y <- sec(2*pi*x)",
        "y <- csc(pi/2*x)",
        "y <- csc(2*pi*x)",
        "y <- sinh(x)",
        "y <- sinh(100*x)",
        "y <- cosh(x)",
        "y <- cosh(100*x)",
        "y <- tanh(x)",
        "y <- tanh(100*x)",
        "y <- coth(x)",
        "y <- sech(100*x)",
        "y <- csch(100*x)",
        "y <- asinh(x)",
        "y <- acosh(1+x)",
        "y <- atanh(x)",
        "y <- acoth(1+x)",
        "y <- asech(x)",
        "y <- acsch(x)",
        "y <- 0.1*sin(10.6*(2*x-1)) + 1.1*(2*x-1)",
        "y <- 0.2*sin(10.6*(2*x-1)) + 1.1*(2*x-1)",
        "y <- 0.2*sin(4*(2*x-1)) +1.1*(2*x-1)",
        "y <- sin(10*pi*x)+x",
        "y <- (x+1)/(x-1)",
        "y <- exp(x) / x",
        "y <- exp(x) / x^2",
        "y <- log(x)/x",
        "y <- exp(x) / log(x)",
        "y <- exp(x) / sin(pi/2*x)",
        "y <- exp(x) / cos(pi/2*x)",
        "y <- sin(pi*x)/(pi*x)",
        "y <- 10*x*sin(10*x)",
        "y <- sigmoid(x-0.5)",
        "y <- logit(x)",
        "y <- (50*x)^(50*x)",
        "y <- einsteinF(1, x)",
        "y <- einsteinF(1, 1000*x)",
        "y <- einsteinF(2, x)",
        "y <- einsteinF(2, 1000*x)",
        "y <- einsteinF(3, x)",
        "y <- einsteinF(3, 1000*x)",
        "y <- einsteinF(4, x)",
        "y <- einsteinF(4, 1000*x)",
        "y <- expint_E1(x)",
        "y <- expint_E1(300*x)",
        "y <- Si(10*x)",
        "y <- Ci(10*x)",
        "y <- Shi(x)",
        "y <- Shi(300*x)",
        "y <- Chi(x)",
        "y <- Chi(300*x)",
        "y <- fresnelS(4*x)",
        "y <- fresnelC(4*x)",
        "y <- erf(x)",
        "y <- erf(300*x)",
        "y <- erfinv(x)",
        "y <- gamma(x)",
        "y <- psi(0, x)",
        "y <- psi(1, x)",
        "y <- psi(2, x)",
        "y <- psi(3, x)",
        "y <- zeta(x+1)",
        "y <- bessel_Yn(0, x)",
        "y <- bessel_Yn(1, x)",
        "y <- bessel_Yn(2, x)",
        "y <- beta(1,x)",
        "y <- eta(x)",
        "y <- eta(1000*x)",
        "y <- einsteinF(1,  x)",
        "y <- beta(1, x)"
    )

    expressions <- c(
        "'Identical'",
        "'Linear'",
        "'Quadratic'",
        "'Square Root'",
        "'Fourth Root'",
        "'Reciprocal'",
        "'Cubic'",
        "'Exponential'",
        "'Exponential #2'",
        "'Exponential #3'",
        "'Exponential base=2'",
        "'Exponential base=2 #2'",
        "'Exponential base=10'",
        "'Exponential base=10 #2'",
        "'Logarithm'",
        "'Sine [one period)'",
        "'Cosine [one period]'",
        "'Tangent [one period]'",
        "'Cotangent [one period]'",
        "'I-Sine'",
        "'I-Cosine'",
        "'I-Tangent'",
        "'I-Cotangent'",
        "'Quadratic [Symmetry]'",
        "'Cubic 2'",
        "'Cubic 3'",
        "'Cubic [Y-stretched]'",
        "'Circle'",
        "'Power #1'",
        "'Power #2'",
        "'Rational'",
        "'Hook'",
        "'Step'",
        "'L-shaped'",
        "'Piecewise'",
        "'Spike'",
        "'Lopsided L-shaped'",
        "'Sine'",
        "'Sine [Two Periods]'",
        "'Sine [Low Freq]'",
        "'Sine, Non-Fourier Freq [Low]'",
        "'Sine [High Freq]'",
        "'Cosine'",
        "'Cosine, Non-Fourier Freq [Low]'",
        "'Cosine [High Freq]'",
        "'Tangent'",
        "'Cotangent'",
        "'Sine, Varying Freq [Medium]'",
        "'Cosine, Varying Freq [Medium]'",
        "'Secant'",
        "'Secant [one period]'",
        "'Cosecant'",
        "'Cosecant [one period]'",
        "'H-Sine'",
        "'Hyperbolic Cosine #1'",
        "'H-Cosine'",
        "'Hyperbolic Tangent #1'",
        "'H-Tangent'",
        "'Hyperbolic Cotangent #1'",
        "'H-Cotangent'",
        "'H-Secant'",
        "'H-Cosecant'",
        "'I-H-Sine'",
        "'I-H-Cosine'",
        "'I-H-Tangent'",
        "'I-H-Cotangent'",
        "'I-H-Secant'",
        "'I-H-Cosecant'",
        "'Linear+Periodic'",
        "'Linear + Periodic, High Freq 2'",
        "'Linear+Periodic, Low Freq'",
        "'Linear + Periodic [Medium Freq]'",
        "'Rational Function'",
        "'Hoerl Function'",
        "'Exponential / Quadratic'",
        "'Logarithm / Linear'",
        "'Exponential / Logarithm'",
        "'Exponential / Sine'",
        "'Exponential / Cosine'",
        "'Sinc Function'",
        "'Catastrophic Sine'",
        "'Sigmoid Function'",
        "'Logit Function'",
        "'Power Exponential'",
        "'Einstein Function1'",
        "'Einstein function1 #2'",
        "'Einstein function2 #1'",
        "'Einstein function2 #2'",
        "'Einstein function3 #1'",
        "'Einstein function3 #2'",
        "'Einstein function4 #1'",
        "'Einstein function4 #2'",
        "'Exponential Integral'",
        "'Exponential Integral #2'",
        "'Sine Integral'",
        "'Cosine Integral'",
        "'H-Sine Integral'",
        "'Hyperbolic Sine Integral #2'",
        "'H-Cosine Integral'",
        "'Hyperbolic Cosine Integral #2'",
        "'Fresnel Sine Integrals'",
        "'Fresnel Cosine Integrals'",
        "'Error Function'",
        "'Error Function #2'",
        "'I-Error Function'",
        "'Gamma Function'",
        "'Psi Function'",
        "'Psi Function #2'",
        "'Psi Function #3'",
        "'Psi Function #4'",
        "'Riemann Zeta Function'",
        "'Bessel Function'",
        "'Bessel Function #2'",
        "'Bessel Function #3'",
        "'Beta Function'",
        "'Dirichlet Eta Function'",
        "'Dirichlet Eta Function #2'",
        "'Einstein Function1'",
        "'Beta Function'"
    )
    return(list(y_funs = y_funs,
                expressions = expressions))
}

#' @export
y_funs_level_label <- function() {
    do.call("cbind", selected_y_funs117_with_expressions()) %>%
        as.data.frame() %>%
        set_names(c("level", 'label')) -> y_funs_level_label_df
    return(y_funs_level_label_df)
}

#' @export
selected_y_funs <- selected_y_funs117_with_expressions()

#' @export
.selected_y_funs <- selected_y_funs117_with_expressions()$y_funs

#' @export
.selected_y_funs_expressions <- selected_y_funs117_with_expressions()$expressions

